name: MBedwarsBetterTeamSelectorAddon
version: 1.1.2
api-version: 1.13
depend: [MBedwars]
authors:
  - dejwideek
  - Marcel Seibel (aka Marcely1199)
  - bakkbone
main: pl.dejwideek.teamselector.TeamSelectorPlugin